### ISSUE TITLE
Absolute reference to `/data` prevents the page from loading when not deployed

### ISSUE THREAD

**Issue by elefeint** [jsheng112/step#10]
I cheat and check the front-end by opening files locally. This works for relative links ("data") but not for absolute links ("/data").

Definitely not a big deal, but I also wanted to show an example of creating an issue from the line of code in GitHub (click to the left on the line of code, click triple dots, click "reference in new issue").

https://github.com/jsheng112/step/blob/cd0e8c7d30e5c7d69acc6d8c16670cee1e8be1c3/portfolio/src/main/webapp/blog.html#L21

**Comment by elefeint** [comment]
Ah, I just realized that data page does not exist yet, so I guess this fix would not help!

**Comment by meltsufin** [comment]
I'm not sure I'm following "check front-end by opening files locally". I thought the `/data` is for the servlet. So, you can't open it locally without running the app.

**Comment by elefeint** [comment]
You can check HTML/CSS/Javascript from the filesystem; it's faster than running the app.
But now that everyone is moving into building out backend, this will be less useful.

**Comment by elefeint** [comment]
So yes, for `/data` specifically, this would not work; it's only useful for static files under webapp.

**Comment by meltsufin** [comment]
So, is this still an issue though? Are you saying it should be changed to a relative path, just for consistency with static pages?

**Comment by elefeint** [comment]
That depends on whether the webapp will ever get deployed to anything but the root of a hostname. So, if you deploy it to "/", it will work. If you deploy it to "/portfolio", it will not.

**Comment by jsheng112** [comment]
by using relative path, do you mean "./data" instead of "/data"?

**Comment by elefeint** [comment]
Or just "data".
